### ISSUE TITLE
Feature Suggestion : split into 2 mods

### ISSUE THREAD

**Issue by troyere** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#176]
**Describe your problem.**
The mod is very intrusive, replacing too much of the generated world : when using with Terralith, Terrablender, Biomes o plenty, the mod seems to crush other mods biomes. Terrablender might be the origin of the problem.

**Describe your suggestion.**
Separate your mod in two : one who is fully intrusive (same as the actual one), and another one who just add biomes wihout terrablender or any intrusive features (a datapack for example).

**Comment by UHQ-GAMES** [comment]
sadly Terrablender is the best way to add new biomes, it allows biomes to exist in the same parameter separated by regions. you can use our config to turn down our region weights and that will help. As for for splitting into two mods, that something id do, especially since pretty much any other way of adding the biomes to the world would be way more intrusive then it already is.
