### ISSUE TITLE
Feature Suggestion: Quicksand removal

### ISSUE THREAD

**Issue by MysticcX** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#4]
**Describe your suggestion.**
Quicksand generation removal via config

**Additional context**
Please add an option to remove quicksand from generating in the overworld via config or at least patch frequency slider, It is repetitive needing to dig up sand every dozen of blocks often causing your horse to suffocate without being able to do anything about it.

**Comment by Teralitha** [comment]
While quicksand is quite jarring the first time you run into it, it is the same way with the vanilla snow traps.  You just dig yourself out of it.  There is a barely noticeble color variation from regular sand.  But I think I would be happy if there was a config toggle to turn it off, since I also hate it, and the snow traps.

**Comment by UHQ-GAMES** [comment]
Sadly configs can't really change features like that anymore, however is can be removed from the biome manually by making a datapack. I will see about changing its spawn frequency for v0.5.0 but I'll most likely be keeping its spawn heights and texture

**Comment by UHQ-GAMES** [comment]
lowered spawnrate of quicksand pits and locked generation height to below Y:68
