### ISSUE TITLE
Please add biome tags.

### ISSUE THREAD

**Issue by crispytwig** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#52]
Please add biome tags for your biomes so other mods can determine things like mobs, blocks, or ores spawning in your biomes. Thanks!

**Comment by UHQ-GAMES** [comment]
biome tags are already used abundantly for all biomes in the mod, this is where all the datagenned tags are

https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/main/src/generated/resources/data

**Comment by UHQ-GAMES** [comment]
if you are referring to custom tags to group biomes together then that could be something I could do for a future update

**Comment by KirboSoftware** [comment]
For full disclosure @crispytwig we make use of vanilla biome tags, modloader tags and even have compat built-in for naturalist (the fabric side still has them, looks like the forge side forgot to add them during the 0.5.x update cycle). I will add the stuff on the forge stuff again so you don't have to worry about adding compat yourself since we already had it added 👍

**Comment by crispytwig** [comment]
> For full disclosure @crispytwig we make use of vanilla biome tags, modloader tags and even have compat built-in for naturalist (the fabric side still has them, looks like the forge side forgot to add them during the 0.5.x update cycle). I will add the stuff on the forge stuff again so you don't have to worry about adding compat yourself since we already had it added 👍

Hi yeah! Sorry for not responding here -- I'm used to mods having their tags outside of the generated resources so I didn't look there initially. UHQ joined our server and we spoke about it some more - thanks for clarifying though!
