### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by OskarMZ** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#6]
**Cannot mine stone (or any other pickaxe-type block)**
With the mod enabled I'm unable to mine stone with any pickaxe, on a server.

**How To Reproduce**
Steps to reproduce the bug: Use the mods on a server. It works fine in single-player but not on multiplayer (identical mods). Using "load my fucking tags" solves the problem, but I think LMFT is causing other issues for me. Can link the mods used as a .zip if needed, sorry never submitted a bug report.

**Version**
Minecraft Version: 1.19.4

Modloader Version: Fabric 0.14.21

Mod Version: 
RegionsUnexploredFabric-0.4.1+1.19.4.jar
RegionsUnexploredFabric-0.4.0+1.19.4.jar

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/49291094/b8ffe3e5-93eb-451a-ac75-bb82d2b3ec43)

**Comment by UHQ-GAMES** [comment]
sorry it seems my reply never sent, would you by chance still have a log from the server from when this happend?

**Comment by OskarMZ** [comment]
[latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12062636/latest.log)


Re-ran the server without LMFT.

**Comment by UHQ-GAMES** [comment]
[20:26:27] [Worker-Main-1/ERROR]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: modern_glass_doors:iron_glass_door (from fabric), modern_glass_doors:iron_glass_trapdoor (from fabric)

looks like its being caused by modern_glass_doors, seems like a lot of their tags are broken
